# 送信状況の取得
call_status:
  url: /call/status.json
  param: { module: call, action: status, sf_format: json }
  requirements: { sf_method: [get] }
# 送信
call_send:
  url: /call/send.json
  param: { module: call, action: send, sf_format: json }
  requirements: { sf_method: [post] }
# boundioの更新取得
call_update:
  url: /call/update.json
  param: { module: call, action: update, sf_format: json }
  requirements: { sf_method: [post] }
# 送信件数の取得
call_count:
  url: /call/count.json
  param: { module: call, action: count, sf_format: json }
  requirements: { sf_method: [get] }
